before_build:  
  - restore_packages.bat

configuration: Release

on_success:
  - nuget pack JsonLd.Entities.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - appveyor PushArtifact JsonLd.Entities.%APPVEYOR_BUILD_VERSION%.nupkg